### ISSUE TITLE
[1.16.5]Server Crash

### ISSUE THREAD

**Issue by SkullDiamond** [JacksonPlayz/mannequins#11]
### What version are you seeing the problem on?

1.16.x

### Describe the issue

```markdown
Server crash on startup
```

### latest.log

```shell
https://pastebin.com/WRdrF0gy
```

**Comment by TheJessaChannel** [comment]
I have the same crash: https://pastebin.com/pRGXpxB1

**Comment by jacksonhardaway** [comment]
Does this only happen on 1.16?

**Comment by XGuidedx** [comment]
I have the same issue as well, crashes on server on startup. Internal game sever crashes when loading a map. 

[crash-2022-02-27_01.45.01-fml.txt](https://github.com/MoonflowerTeam/mannequins/files/8148200/crash-2022-02-27_01.45.01-fml.txt)

**Comment by VanilaBOI** [comment]
Man am I relieved that I'm not the only one having this Issue
[crash-2022-03-03_00.44.03-fml.txt](https://github.com/MoonflowerTeam/mannequins/files/8173695/crash-2022-03-03_00.44.03-fml.txt)
.

**Comment by SirOMGitsYOU** [comment]
I'm also experiencing the crash, it looks like it's loading client-side features on Server side then crashes

**Comment by jacksonhardaway** [comment]
Fixed, update mannequins and pollen
